Removed outcome defaults - In Progress
department-of-veterans-affairs/GIBCT-Data-Service pull request #223
Opened 2017-03-13 16:36 UTC by mphprogrammer

1. Fixes issue with NULL values reported as 0 in outcomes

2017-03-14 17:51 UTC, mphprogrammer commented
@saintsoup52 @saneshark There are no caution flag Issues remaining that needed to be addressed. In the sample_csvs directory, I've slapped together a spreadsheet that does side by side comparisons with the old and new GIDS. The only differences I can find are text case, spaces following commas, and reason ordering in the messages. The spreadsheet is called verify.xlsx.

2017-03-14 21:03 UTC, mphprogrammer commented
@saintsoup52 @saneshark Disregard last remark - both old and new gids agree completely regarding caution flags and caution flag reasons.

2017-03-15 16:58 UTC, saneshark commented
@mphprogrammer This LGTM please feel free to merge when you are ready.

2017-03-15 16:58 UTC, saneshark approved these changes

2017-03-15 16:59 UTC, saneshark requested changes
Dont change existing migration

2017-03-15 17:00 UTC, saneshark commented
@mphprogrammer I spoke too fast. Please don't modify existing migrations. Create a new migration to change defaults instead.

2017-03-15 18:08 UTC, saneshark commented on db/schema.rb
> +    t.float    "transfer_out_rate_veteran"
@mphprogrammer missing one here

2017-03-15 18:13 UTC, saneshark approved these changes

2017-03-15 18:13 UTC, saneshark commented
LGTM

2017-03-15 18:21 UTC, merged

2017-03-21 10:12 UTC, saintsoup52 commented
Not sure where we are with this... but the latest "verify file" (see link below) is still very different then the one in the old DS.

2017-03-21 15:47 UTC, mphprogrammer commented
@saintsoup The old gids data used in verify I produced myself from my local copy of the current Data service. Along the errors you had mentioned, verify.xslx didn't find any differences between institution_new.csv and institution_old.csv, what differences in these csvs did you find?

2017-03-21 15:48 UTC, mphprogrammer commented
@saintsoup52 also, there was no "link below" :-)

2017-03-21 19:33 UTC, saintsoup52 commented
I just used the data dashboard "data validation" worksheet to compare the final products and those screenshots I sent you were the results. 

I created the data validation worksheet (which can be downloaded with the dashboards) to run a side by side comparison and detect where there are differences. It was to make sure there were no major variances when we update the data week to week.

2017-03-22 13:42 UTC, mphprogrammer commented
Did you use the `institution_old.csv` and `institution_new.csv` files to do that comparison?