19451: Add ability to upload SCO file to GIDS
department-of-veterans-affairs/GIBCT-Data-Service pull request #415
Opened 2019-08-14 19:13 UTC by elder-joseph

## Description
As an EDU team member, I need the ability to upload School Certifying Official data to GIDS so that it can be used to display information in the Comparison Tool.

https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/vets.gov-team/19451

## Testing done
Local manual and unit/spec tests pass successfully, additional unit test added for new file type.

## Acceptance criteria
- [x] A user can upload a .csv file containing SCO data matching the format outlined in Supporting Artifact # 1 into the GIDS Tool.
- [x] A user can export the most recently uploaded SCO data from the GIDS Tool.

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2019-08-14 19:44 UTC, shawkey-daniel requested changes
WeamsCertifyingOfficials should be singular.

2019-08-14 19:47 UTC, dmccurdybah commented on app/models/weams_certifying_officials.rb
> +  COLS_USED_IN_INSTITUTION = %i[closure109].freeze
I think this can be removed

2019-08-19 14:28 UTC, shawkey-daniel requested changes

2019-08-19 14:28 UTC, shawkey-daniel commented on spec/models/version_spec.rb
> +
Please remove this extra whitespace

2019-08-19 14:33 UTC, ksantiagomorgan6 commented on spec/models/version_spec.rb
> +
White space removed

2019-08-19 14:44 UTC, shawkey-daniel approved these changes
LGTM

2019-08-19 18:43 UTC, sonntag-adam approved these changes

2019-08-20 14:17 UTC, jholton approved these changes
LGTM

2019-08-20 14:59 UTC, merged

2019-09-04 14:39 UTC, ksantiagomorgan6 commented
updated headers

https://github.com/department-of-veterans-affairs/gibct-data-service/pull/434