DB Migration - Update Institution Programs index
department-of-veterans-affairs/GIBCT-Data-Service pull request #447
Opened 2019-09-23 19:38 UTC by dmccurdybah

2019-09-23 19:48 UTC, shawkey-daniel requested changes

2019-09-23 19:48 UTC, shawkey-daniel commented on db/migrate/20190923145100_update_institution_programs_index.rb
> +              [:facility_code, :description,:version],
Missing a space after :description,

2019-09-24 18:38 UTC, shawkey-daniel approved these changes
LGTM

2019-09-24 18:52 UTC, jholton approved these changes
LGTM

2019-09-24 19:00 UTC, merged