19829: CT: Address RSpec/ContextWording rubocop errors in GIDS
department-of-veterans-affairs/GIBCT-Data-Service pull request #473
Opened 2019-10-24 19:37 UTC by elder-joseph

## Description
As a developer, I need to address the RSpec/ContextWording rubo-cop errors so that the codebase is more secure and stable.

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19829

## Testing done
Tests pass locally

## Acceptance criteria
- [ ] There are no longer any of the following offenses: RSpec/ContextWording: # Offense count: 38

2019-10-24 19:38 UTC, zurbergram approved these changes
LGTM

2019-10-24 19:45 UTC, shawkey-daniel requested changes

2019-10-24 19:45 UTC, shawkey-daniel commented on spec/controllers/shared_examples/shared_examples_for_authentication.rb
> +    context 'when when authenticated' do
When when?

2019-10-24 19:46 UTC, elder-joseph commented on spec/controllers/shared_examples/shared_examples_for_authentication.rb
> +    context 'when when authenticated' do
Woops, I will correct that one

2019-10-28 17:23 UTC, sonntag-adam approved these changes

2019-10-29 17:09 UTC, jholton approved these changes
LGTM

2019-10-29 17:57 UTC, shawkey-daniel approved these changes
LGTM

2019-10-29 17:58 UTC, merged