update specs to satisfy AnyInstance requirment
department-of-veterans-affairs/GIBCT-Data-Service pull request #480
Opened 2019-10-28 18:21 UTC by ksantiagomorgan6

## Description
Update various files to pass `AnyInstance` cop

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19828

## Testing done
Ran `bundle exec rake ci` to confirm no rubucop offenses are generated. 

## Screenshots

## Acceptance criteria
- [x] No errors thrown when running `bundle exec rake ci`

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2019-10-29 13:27 UTC, shawkey-daniel requested changes

2019-10-29 13:27 UTC, shawkey-daniel commented on spec/models/gibct_site_mapper_spec.rb
> +    it 'sets the default host' do
This statement does not appear to match the test.

2019-10-29 13:27 UTC, shawkey-daniel commented on spec/models/gibct_site_mapper_spec.rb
> +    it 'sets SitemapGenerator::Sitemap.default_host' do
This statement is not in the correct natural language and does not clearly match the test.

2019-10-29 18:30 UTC, shawkey-daniel requested changes

2019-10-29 18:30 UTC, shawkey-daniel commented on spec/models/gibct_site_mapper_spec.rb
> +    it 'sets the default host and creates a sitemap' do
This one is checking the sitemap URI

2019-10-29 18:30 UTC, shawkey-daniel commented on spec/models/gibct_site_mapper_spec.rb
> +    it 'sets default_host to www.va.gov/gi-bill-comparison-tool' do
This one is checking the default host URI

2019-10-29 19:25 UTC, shawkey-daniel approved these changes
LGTM

2019-10-30 13:21 UTC, sonntag-adam approved these changes

2019-10-30 14:50 UTC, LindseySaari approved these changes
👍

2019-10-30 15:10 UTC, merged