add vet tec progam data to serializer
department-of-veterans-affairs/GIBCT-Data-Service pull request #489
Opened 2019-11-04 13:30 UTC by hughes-dustin

## Description
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/vets.gov-team/19870

Backend changes needed for 19870.

## Testing done

## Screenshots

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2019-11-04 13:40 UTC, devin-mccurdy approved these changes
LGTM

2019-11-04 19:34 UTC, annaswims requested changes
please give a description of your change in the pull request body (not just a link to an issue) and make migrations in a separate PR.

2019-11-04 19:53 UTC, annaswims approved these changes
LGTM

2019-11-06 12:41 UTC, delli-gatti-michael approved these changes

2019-11-06 15:16 UTC, merged