4044: Add parent institution relationship to SCO & Program data
department-of-veterans-affairs/GIBCT-Data-Service pull request #527
Opened 2019-12-17 20:09 UTC by elder-joseph

## Description
As a developer, I need to add a parent relationship to the SCO and Program data so that the database is more normalized.

https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/4044

## Testing done
Testing passes locally

## Screenshots
N/A

## Acceptance criteria
- [x] Has_many relationship is established from institution to institution_program.
- [x] Has_many relationship is established from institution to versioned_school_certifying_official.
- [x] Archiver is configured to archive institution_program and versioned_school_certifying_official data.

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2019-12-20 14:10 UTC, shawkey-daniel requested changes
Minor changes

2019-12-20 14:10 UTC, shawkey-daniel commented on app/models/institution_builder.rb
> +    str += " JOIN versions v ON v.number = #{version_number}"
Please make this INNER JOIN for clarity.

2019-12-20 14:10 UTC, shawkey-daniel commented on app/models/institution_builder.rb
>        ?,
Please make this v.number then pass in version_number once.

2019-12-20 14:10 UTC, shawkey-daniel commented on app/models/institution_builder.rb
> +      FROM weams JOIN versions v ON v.number = ?
INNER JOIN

2019-12-20 19:15 UTC, sonntag-adam approved these changes

2020-01-02 14:03 UTC, shawkey-daniel requested changes

2020-01-02 14:03 UTC, shawkey-daniel commented on db/schema.rb
> +    t.index ["version_id"], name: "index_zipcode_rates_archives_on_version_id"
Drop indexes on archives.

2020-01-02 21:07 UTC, shawkey-daniel approved these changes
LGTM

2020-01-07 18:57 UTC, jholton approved these changes
LGTM.
Is `VersionedSchoolCertifyingOfficial` going away after this?

2020-01-07 19:28 UTC, elder-joseph commented
@jholton In an effort to normalize the data, `VersionedSchoolCertifyingOfficial` could go away after this

2020-01-07 19:34 UTC, merged