4063: Setup parent/child version relationships for institutions and zip code rates.
department-of-veterans-affairs/GIBCT-Data-Service pull request #529
Opened 2019-12-19 18:26 UTC by elder-joseph

## Description
As a developer, I need to add a parent / child relationship so that the database is more normalized.

This PR is specific to the GIDS app source code, there is a separate PR associated with the DB changes for 4063: https://github.com/department-of-veterans-affairs/gibct-data-service/pull/519

https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/4063

## Testing done
Testing passes locally 

## Screenshots
N/A

## Acceptance criteria
- [x] Version table is created.
- [x] Has_many relationship is established from version to institution.
- [x] Has_many relationship is established from version to zipcode_rate.
- [x] Archiver is configured to archive institution and zipcode_rate data.

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2019-12-20 13:53 UTC, shawkey-daniel requested changes
Minor changes.

2019-12-20 13:53 UTC, shawkey-daniel commented on app/models/institution_builder.rb
> +    str += " JOIN versions v ON v.number = #{version_number}"
Please make this INNER JOIN for clarity.

2019-12-20 13:53 UTC, shawkey-daniel commented on app/models/institution_builder.rb
>        ?,
Change to v.number and pass version_number once.

2019-12-20 13:53 UTC, shawkey-daniel commented on app/models/institution_builder.rb
> +      FROM weams JOIN versions v ON v.number = ?
INNER JOIN for clarity.

2019-12-20 18:32 UTC, sonntag-adam approved these changes

2020-01-03 18:45 UTC, shawkey-daniel approved these changes
LGTM

2020-01-06 22:19 UTC, jholton approved these changes

2020-01-07 19:10 UTC, merged