10983: Add Scorecard alias data element to version data
department-of-veterans-affairs/GIBCT-Data-Service pull request #695
Opened 2020-08-05 17:05 UTC by elder-joseph

## Description
As a developer, I need to add the Scorecard alias data element to the API pull request in GIDS so that the data can be included in version generation for search.

Originating Issue: [10983](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/10983)

## Testing done
CI passes locally, manual checks of columns in database as well.

## Screenshots
![Screen Shot 2020-08-05 at 1 03 11 PM](https://user-images.githubusercontent.com/48804834/89442019-0e77a680-d71c-11ea-9a75-3edc8ae31fcf.png)

## Acceptance criteria
- [x] The alias data element is retrieved and stored by the API Fetch request within GIDS.
- [x] The alias data element is included in the version generation.
- [x] The comparison tool search functionality includes the scorecard data element when a search is executed.

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2020-08-05 17:25 UTC, zurbergram requested changes
at https://github.com/department-of-veterans-affairs/gibct-data-service/blob/master/app/models/institution_builder.rb#L318

update the sql to have `ialias = scorecard.alias` instead
```
UPDATE institutions SET #{columns_for_update(Scorecard)}, ialias = scorecard.alias
      FROM scorecards
      WHERE institutions.cross = scorecards.cross
      AND institutions.version_id = #{version_id}
```

2020-08-05 17:25 UTC, zurbergram commented on app/models/institution.rb
> +    'alias LIKE :upper_contains_term'
This is not needed

2020-08-05 17:25 UTC, zurbergram commented on app/models/institution.rb
> +    'alias' => { column: :alias, converter: BaseConverter },
This is not needed

2020-08-05 17:25 UTC, zurbergram commented on app/models/scorecard.rb
> +    hbcu menonly womenonly relaffil hcm2 pctfloan alias
This is not needed

2020-08-05 17:25 UTC, zurbergram commented on app/utilities/scorecard_api/service.rb
> +      'school.alias': :alias
Styling: move this to be with other school properties

2020-08-05 17:25 UTC, zurbergram commented on db/migrate/20200804170036_add_alias_to_institutions.rb
> +class AddAliasToInstitutions < ActiveRecord::Migration[5.2]
This is not needed

2020-08-05 17:25 UTC, zurbergram commented on db/migrate/20200804170056_add_alias_to_institutions_archives.rb
> +class AddAliasToInstitutionsArchives < ActiveRecord::Migration[5.2]
This is not needed

2020-08-05 17:25 UTC, zurbergram commented on spec/controllers/v0/institutions_controller_spec.rb
> +      create(:institution, :independent_study, alias: 'UIS', version_id: Version.current_production.id)
This is not needed

2020-08-05 17:26 UTC, shawkey-daniel requested changes
I think we also want to remove ialias from institution. I don't want anyone to get confused by the two values.

2020-08-05 17:46 UTC, elder-joseph commented
@shawkey-daniel I had considered adding a migration to remove that, but wasnt sure if we wanted to keep it around for some reason or another as the story said "includes" the alias from scorecard. Looks like going with Matt's suggestions here it will remain, but `ialias` will get the value from scorecard instead.

2020-08-05 18:08 UTC, zurbergram approved these changes

2020-08-05 19:21 UTC, shawkey-daniel approved these changes
LGTM

2020-08-14 18:38 UTC, delli-gatti-michael approved these changes

2020-08-17 13:42 UTC, f1337 approved these changes
Looks good to me! :thumbsup:
![Shaun The Sheep giving thumbs up and smiling](https://media.giphy.com/media/tIeCLkB8geYtW/giphy.gif)

2020-08-24 12:45 UTC, merged