16357: Add lat and lon to institutions
department-of-veterans-affairs/GIBCT-Data-Service pull request #774
Opened 2020-11-23 15:43 UTC by elder-joseph

## Description
As a developer, I need to include the latitude and longitude in version generation so that it can be used for any forthcoming mapping / near me functionality.

When testing with the local set of sample CSVs, only 9599 of the 69343 institutions have latitude values and 9600 of the same 69343 have longitude values.

Note: Longitude is supplied as `longitud` from the `ipeds_hd` csv file.

[Originating Issue](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/16357)

## Testing done
CI tests pass locally.

## Screenshots
N/A

## Acceptance criteria
- [x] Analysis of data coverage of institutions with/without latitude and/or longitude is documented on this story.
- [x] Institution Latitude is:
a. included in version generation.
b. included in the institution export.
c. available to be used by the front end of the Comparison Tool
- [x] Institution Longitude is:
a. included in version generation.
b. included in the institution export.
c. available to be used by the front end of the Comparison Tool

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2020-11-23 15:47 UTC, zurbergram commented on app/models/institution.rb
> +    'longitud' => { column: :longitud, converter: NumberConverter }
```suggestion
    'longitude' => { column: :longitud, converter: NumberConverter }
```

2020-11-24 16:58 UTC, zurbergram requested changes

2020-11-24 16:58 UTC, zurbergram commented on app/models/institution_builder.rb
> +  def self.update_lat_lon_from_scorecard(version_id)
This is not needed as column is set from scorecard at https://github.com/department-of-veterans-affairs/gibct-data-service/blob/master/app/models/institution_builder.rb#L303

2020-11-24 16:58 UTC, zurbergram commented on app/models/ipeds_hd.rb
> +  COLS_USED_IN_INSTITUTION = %i[vet_tuition_policy_url f1sysnam f1syscod latitude].freeze
This is not needed since you are manually adding the column in `institution_builder`

2020-11-24 17:31 UTC, zurbergram approved these changes

2020-11-30 15:35 UTC, sonntag-adam approved these changes

2020-11-30 23:59 UTC, thilton-oddball requested changes
So it looks like the migrations were broken out into their own PR (https://github.com/department-of-veterans-affairs/gibct-data-service/pull/775) which is good, but those migrations should be removed from this PR. Otherwise, everything else looks good.

2020-12-01 13:44 UTC, elder-joseph commented
@thilton-oddball no problem, I will address that and remove them from this PR.

2020-12-01 14:03 UTC, elder-joseph commented
@thilton-oddball I merged #775 into master then merged master into this branch to effectively remove those lines from this PR.

2020-12-02 16:13 UTC, thilton-oddball approved these changes
Looks good!

2020-12-02 17:44 UTC, merged