CT: Add IPEDS to Caution Flag Mappings #18306
department-of-veterans-affairs/GIBCT-Data-Service pull request #783
Opened 2021-02-02 20:25 UTC by zurbergram

## Description

## Original issue(s)
department-of-veterans-affairs/va.gov-team#18306

## Testing done

## Screenshots

## Acceptance criteria
- [ ]

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2021-02-04 13:17 UTC, shawkey-daniel requested changes

2021-02-04 13:17 UTC, shawkey-daniel commented on app/models/institution_builder.rb
> +              AND "cross" = '180814'
Only for 180814?

2021-02-04 14:29 UTC, zurbergram commented on app/models/institution_builder.rb
> +              AND "cross" = '180814'
that fixed my unit test

2021-02-04 14:38 UTC, shawkey-daniel approved these changes
LGTM

2021-02-08 16:20 UTC, delli-gatti-michael approved these changes

2021-02-09 20:24 UTC, thilton-oddball approved these changes
LGTM

2021-02-10 14:28 UTC, merged