Added CIPCode Csv upload
department-of-veterans-affairs/GIBCT-Data-Service pull request #787
Opened 2021-02-10 19:55 UTC by ksantiagomorgan6

## Description
As a developer, I need to be able to upload the CIP codes into GIDS, so that data can be used to display new information as part of the CT redesign.
## Original issue(s)
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/19572

## Testing done
Local testing 

## Screenshots
![Screen Shot 2021-02-10 at 2 47 28 PM](https://user-images.githubusercontent.com/50601724/107563796-7c12fc80-6baf-11eb-8f56-6fefd84138f2.png)
![Screen Shot 2021-02-10 at 2 50 37 PM](https://user-images.githubusercontent.com/50601724/107563833-87febe80-6baf-11eb-9c91-e8c5ec31548b.png)

## Acceptance criteria
- [x] Db changes included

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2021-02-11 15:46 UTC, shawkey-daniel approved these changes
LGTM

2021-02-11 19:26 UTC, delli-gatti-michael approved these changes

2021-02-11 19:36 UTC, delli-gatti-michael commented
This PR is for adding the ability to upload the data as a CSV only. Because of the format of the expected data, converting to other file types (.txt, .xls, .xlsx) will result in data loss

2021-02-12 21:06 UTC, thilton-oddball approved these changes
LGTM

2021-02-12 21:07 UTC, thilton-oddball requested changes
It looks like you will need to put just the migration and schema change in its own PR.

2021-02-16 18:45 UTC, ksantiagomorgan6 commented
> It looks like you will need to put just the migration and schema change in its own PR and remove them from this PR.

I merged in the db changes and pulled them into this PR

2021-02-17 21:43 UTC, ericboehs approved these changes

2021-02-17 21:43 UTC, ericboehs commented on spec/fixtures/cip_code.csv
> +01,01.00,No substantive changes,no,"Agriculture, General.",Instructional content is defined in code 01.0000.,,
Might want to fix the no new line at end of file. 🤷

2021-02-17 21:48 UTC, thilton-oddball approved these changes

2021-02-18 13:10 UTC, merged