DB migration for cip code csv upload
department-of-veterans-affairs/GIBCT-Data-Service pull request #788
Opened 2021-02-10 19:55 UTC by ksantiagomorgan6

## Description
As a developer, I need to be able to upload the CIP codes into GIDS, so that data can be used to display new information as part of the CT redesign.
## Original issue(s)
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/19572

## Testing done
Local testing 

## Screenshots

## Acceptance criteria
- [x] Db changes included

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2021-02-10 20:18 UTC, shawkey-daniel approved these changes
LGTM

2021-02-11 19:26 UTC, delli-gatti-michael approved these changes

2021-02-12 21:03 UTC, thilton-oddball requested changes

2021-02-12 21:21 UTC, ksantiagomorgan6 commented on app/models/cip_code.rb
> +class CipCode < ImportableRecord
Deleted

2021-02-12 21:22 UTC, thilton-oddball approved these changes
Looks good!

2021-02-16 18:09 UTC, merged