25818: Add ability to upload section 1005 tuition and fees data file
department-of-veterans-affairs/GIBCT-Data-Service pull request #832
Opened 2021-06-15 18:00 UTC by elder-joseph

## Description
As an Education team member, I need the ability to upload a file containing data regarding an institutions compliance with Isakson and Roe section 1005 so that data can be displayed on the Comparison Tool.

`db` specific PR

## Original issue(s)
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/25818

## Testing done
Testing passes locally

## Screenshots
N/A

## Acceptance criteria
- [x] InStateTuitionPolicyUrl table is created

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2021-06-15 18:16 UTC, shawkey-daniel requested changes

2021-06-15 18:16 UTC, shawkey-daniel commented on db/migrate/20210615173005_create_in_state_tuition_policy_urls.rb
> +      t.timestamps
Does this need null: false constraint here?

2021-06-15 18:25 UTC, shawkey-daniel approved these changes
LGTM

2021-06-15 18:27 UTC, zurbergram commented
Where's the PR that uses this table?

2021-06-21 14:53 UTC, delli-gatti-michael approved these changes

2021-06-22 17:17 UTC, LindseySaari approved these changes

2021-06-22 17:23 UTC, merged