Bah 25818
department-of-veterans-affairs/GIBCT-Data-Service pull request #834
Opened 2021-06-16 14:36 UTC by elder-joseph

## Description
As an Education team member, I need the ability to upload a file containing data regarding an institutions compliance with Isakson and Roe section 1005 so that data can be displayed on the Comparison Tool.

## Original issue(s)
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/25818

## Testing done
Testing passes locally

## Screenshots
N/A

## Acceptance criteria
- [x] The file type is "InStateTuitionPolicyUrl".
- [x] The user has the ability to:
a. Import a data file
b. Export a data file
- [x] Accepted import file formats for the data file are:
a. .txt
b. .csv
c. .xls
d. .xlsx
- [x] Valid column delimiters are:
a. ,
b. |
- [x] The accepted imported file has the columns in the following order:
a. Facility Code
b. In-State Tuition Information
- [x] The following columns are required for data to be imported:
a. FacilityCode
b. In-State Tuition Information
- [x] The "In-State Tuition Information" data is included in the institution version generation.

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2021-06-16 19:47 UTC, shawkey-daniel requested changes

2021-06-16 19:47 UTC, shawkey-daniel commented on app/utilities/institution_builder/in_state_tuition_policy_url_builder.rb
> +    def self.add_in_state_tuition_policy_url(version_id)
Can we just call this self.build?

2021-06-16 19:47 UTC, shawkey-daniel commented on db/migrate/20210615232805_add_in_state_tuition_information_to_institutions_archives.rb
> +    add_column :institutions_archives, :in_state_tuition_information, :string
Can we just add this line under the line for institutions? I think they go together

2021-06-16 19:47 UTC, shawkey-daniel commented on db/schema.rb
> +    t.datetime "updated_at", precision: 6, null: false
I don't see precision on any other timestamps. Is this needed?

2021-06-17 13:30 UTC, zurbergram approved these changes

2021-06-17 13:37 UTC, shawkey-daniel approved these changes
LGTM

2021-06-21 14:53 UTC, delli-gatti-michael approved these changes

2021-06-22 14:23 UTC, zurbergram commented
Can you add the `in_state_tuition_information` column to `app/serializers/institution_profile_serializer.rb`

2021-06-22 17:37 UTC, LindseySaari approved these changes
👍

2021-06-22 20:09 UTC, merged