Removed all non APRVD and SUSP schools from school locations section
department-of-veterans-affairs/GIBCT-Data-Service pull request #851
Opened 2021-08-06 14:47 UTC by ksantiagoBAH

## Description
As a developer, I need to remove the display of non-approved institutions from the "School locations" section of the profile pages so that institutions that are not approved for display are not shown in the comparison tool.
## Original issue(s)
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/27657
## Testing done
local testing

## Screenshots

## Acceptance criteria
- [x] Only institutions with the following WEAMS poo status are displayed in the "School locations" section of the profile page:
a. APRVD
b. SUSP

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2021-08-06 15:01 UTC, LindseySaari approved these changes

2021-08-06 15:38 UTC, shawkey-daniel requested changes

2021-08-06 15:38 UTC, shawkey-daniel commented on app/models/institution_tree.rb
> +            WHERE i.version_id = ? AND i.poo_status = 'APRVD' OR i.poo_status = 'SUSP'
I think 

i.poo_status IN ('APRVD', 'SUSP')

is cleaner

2021-08-06 16:00 UTC, shawkey-daniel approved these changes
LGTM

2021-08-11 12:55 UTC, sonntag-adam approved these changes

2021-08-11 12:56 UTC, merged