Bah 28902
department-of-veterans-affairs/GIBCT-Data-Service pull request #859
Opened 2021-08-24 20:28 UTC by elder-joseph

## Description
As a developer, I need to update the ratings data retrieval to only retrieve valid ratings so that the display of ratings information and the calculations accurately reflect the aggregate ratings.

## Original issue(s)
https://github.com/department-of-veterans-affairs/va.gov-team/issues/28902

## Testing done

## Screenshots
N/A

## Acceptance criteria
- [x] Only GIDS "SchoolRating" data rows that contains a rating in at least one of the following categories are included during version generation:
a. overall experience
b. quality of classes
c. online instruction
d. job preparation
e. gi bill support
f. veteran community
g. marketing practices

- [ ] On the CT Redesign search results page:
a. If the institution has the minimum number of ratings, the composite average is displayed on the card.
b. If the institution does not have the minimum number of ratings, "Not yet rated by Veterans" is displayed (replacing current content "School rating: Not yet rated")

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2021-08-25 18:45 UTC, shawkey-daniel requested changes

2021-08-25 19:01 UTC, shawkey-daniel approved these changes
LGTM

2021-08-26 19:23 UTC, sonntag-adam approved these changes

2021-08-30 18:16 UTC, voidspooks approved these changes

2021-08-30 18:50 UTC, merged