Add geo text search coord script
department-of-veterans-affairs/GIBCT-Data-Service pull request #914
Opened 2022-05-10 18:41 UTC by PJart

Added call to full text search in geocoder gem to update institutions with bad addresses.

2022-05-11 16:47 UTC, ericboehs requested changes

2022-05-11 16:47 UTC, ericboehs commented on lib/tasks/fix_coord_mismatch.rake
> +  if city == result.city.titleize || state == result.state || zip == result.zip || vil == result.city.titleize
If this conditional isn't met should you return an empty array here instead of nil?

2022-05-11 16:47 UTC, ericboehs commented on lib/tasks/fix_coord_mismatch.rake
> +    next if ck_srch_fields(result, geo).blank?
You should memoize ck_srch_fields since you're calling it multiple times.

2022-05-11 16:47 UTC, ericboehs commented on lib/tasks/fix_coord_mismatch.rake
>    results = Institution.approved_institutions(version)
This rake file is getting a bit large. It would make sense to extract the logic into a class so that it could be tested easier.

2022-05-17 23:34 UTC, jhwuz reviewed
All of your methods in GeocodeLogic are public but some of them are not used outside the class. Maybe methods like `check_bad_address` and `search_bad_addr` should be private helper methods since they are only used within the class.

2022-05-17 23:34 UTC, jhwuz commented on app/models/geocode_logic.rb
> +  def return_text_search(result, geo, city, state, _num)
```suggestion
  def text_search(result, geo, city, state)
```

2022-05-17 23:34 UTC, jhwuz commented on app/models/geocode_logic.rb
> +  def return_text_search(result, geo, city, state, _num)
Try not to start method names with `return` for readability. Changing the name to `text_search` will still imply that it returns the same result.
 
Is `num` needed here? It's not ever used inside of the method.

2022-05-17 23:34 UTC, jhwuz commented on app/models/geocode_logic.rb
> +  end
```suggestion
  def geocode_fields(result, addresses)
    geocoded_result = Geocoder.coordinates("#{result.city}, #{result.state}, #{result.zip}")
    addresses.each do |address|
      geocoded = Geocoder.coordinates(address)
      if geocoded.present?
        update_mismatch(result, geocoded)
      else
        check_bad_address(result, geocoded_result)
      end
    end
  end
```

2022-05-17 23:34 UTC, jhwuz commented on app/models/geocode_logic.rb
> +  end
Passing in the addresses as an array could help shorten and clean up this method.

2022-05-17 23:34 UTC, jhwuz commented on app/models/search_geocoder.rb
> +    end
```suggestion
    by_address.each do |result|
      addresses = [  parse_add_fields(result, result.address),
                               parse_add_fields(result, result.address_1),
                               parse_add_fields(result, result.address_2) ]
      
      geocode_fields(result, addresses)
    end
```

2022-05-17 23:34 UTC, jhwuz commented on app/models/search_geocoder.rb
> +      end
```suggestion
      else
        addresses = [ parse_add_fields(result, result.address),
                                 parse_add_fields(result, result.address_1),
                                 parse_add_fields(result, result.address_2) ]
        geocode_fields(result, addresses)
      end
```

2022-05-18 16:47 UTC, jhwuz approved these changes

2022-05-18 17:57 UTC, ericboehs approved these changes

2022-05-18 17:57 UTC, merged